### GET request to files status by uuid server
GET http://localhost:8002/files-upload/v1/status/id/cb2a2afb-6f9d-4fb1-a99e-a028701866d0

###

### GET request to files type by uuid server
GET http://localhost:8002/files-upload/v1/status

###

### GET request to files type by uuid server
GET http://localhost:8002/files-upload/v1/type/id/79e027c2-cd2b-4b52-b4a4-4c2ccaafec93

###

