# app database configuration:
spring:
  sql:
    init:
      schema-locations: schema.sql
      data-locations: data.sql
      mode: always

  jpa:
    open-in-view: false                   # Controla si Hibernate debe mantener la sesión abierta durante toda la vista
    show-sql: false
    hibernate:
      ddl-auto: create-drop                     # Puede ser: none, validate, update, create, create-drop
    properties:
      hibernate:
        format_sql: false                  # Formatea las consultas SQL para mayor legibilidad
        show_sql: false                    # Muestra las consultas SQL ejecutadas
    defer-datasource-initialization: true
  datasource:

    # URL de la base de datos
    url: jdbc:h2:tcp://localhost/~/test                 #;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa                          # Nombre de usuario por defecto
    password:                            # Sin contraseña por defecto
    driver-class-name: org.h2.Driver

    # Configuración del pool de conexiones HikariCP
    #hikari:
    #  maximum-pool-size: 20               # Tamaño máximo del pool de conexiones
    #  minimum-idle: 10                    # Mínimo de conexiones inactivas en el pool
    #  connection-timeout: 3000            # Tiempo máximo (en milisegundos) para obtener una conexión del pool
    #  idle-timeout: 600000                # Tiempo máximo (en milisegundos) que una conexión puede estar inactiva en el pool
    #  max-lifetime: 1800000               # Tiempo máximo de vida de una conexión en milisegundos
    #  validation-timeout: 5000            # Tiempo de espera para validar las conexiones
    #  connection-test-query: SELECT 1     # Consulta para probar la conexión (opcional)
    #  leak-detection-threshold: 45000     # Umbral para detectar fugas de conexión
    #  pool-name: HikariCP-Pool            # Nombre del pool de conexiones
    #  connection-init-sql: SELECT 1       # Consulta SQL que se ejecuta al inicializar la conexión
    #  allow-pool-suspension: false        # Permitir la suspensión del pool
    #  auto-commit: true                   # This property controls the default auto-commit behavior of connections returned from the pool. It is a boolean value, default: true


  # Configuración adicional de H2 para pruebas (si usas H2 para tests, puedes agregar esta sección)
  h2:
    console:
      enabled: true                       # Habilitar la consola web de H2 (si usas H2)
      #settings:
        #trace: true
        #web-admin-password: sa
        #web-allow-others: false
      path: /h2-console # Ruta para acceder a la consola