-- Create the schema if it doesn't exist
-- CREATE SCHEMA IF NOT EXISTS DEMO;
-- Create the DATA_STATUS table first

CREATE TABLE IF NOT EXISTS DATA_STATUS (
    DS_ID NUMERIC NOT NULL AUTO_INCREMENT CONSTRAINT DATA_STATUS_PK PRIMARY KEY,
    DS_UUID VARCHAR(36) NOT NULL,
    DS_NAME VARCHAR(100) NOT NULL,
    DS_DESCRIPTION VARCHAR(100) NOT NULL,
    DS_CREATED TIMESTAMP(6) NOT NULL
);

-- Create the DATA_TYPE table first

CREATE TABLE IF NOT EXISTS DATA_TYPE (
    DT_ID NUMERIC NOT NULL AUTO_INCREMENT CONSTRAINT DATA_TYPE_PK PRIMARY KEY,
    DT_UUID VARCHAR(36) NOT NULL,
    DT_NAME VARCHAR(100) NOT NULL,
    DT_DESCRIPTION VARCHAR(100) NOT NULL,
    DT_CREATED TIMESTAMP(6) NOT NULL
);

-- Create the DATA_FILE table first

CREATE TABLE IF NOT EXISTS DATA_FILE (
    DF_ID NUMERIC NOT NULL AUTO_INCREMENT CONSTRAINT DATA_FILE_PK PRIMARY KEY,
    DF_UUID VARCHAR(36) NOT NULL,
    DF_NAME VARCHAR(100) NOT NULL,
    DF_TYPE NUMERIC NOT NULL CONSTRAINT DATA_FILE_FK1 REFERENCES DATA_TYPE(DT_ID),
    DF_STATUS NUMERIC NOT NULL CONSTRAINT DATA_FILE_FK2 REFERENCES DATA_STATUS(DS_ID),
    DF_SIZE NUMBER, DL_CREATED TIMESTAMP(6) NOT NULL
);

-- Create the DATA_BASIC table first

CREATE TABLE IF NOT EXISTS DATA_BASIC (
    DB_ID NUMERIC NOT NULL AUTO_INCREMENT CONSTRAINT DATA_BASIC_PK PRIMARY KEY,
    DB_UUID VARCHAR(36) NOT NULL,
    DB_NAME VARCHAR(100) NOT NULL,
    DB_STATUS NUMERIC NOT NULL CONSTRAINT DATA_BASIC_FK2 REFERENCES DATA_STATUS(DS_ID),
    DB_CREATED TIMESTAMP(6) NOT NULL
);

-- Create the DATA_ADVANCE table first

CREATE TABLE IF NOT EXISTS DATA_ADVANCE (
    DA_ID NUMERIC NOT NULL AUTO_INCREMENT CONSTRAINT DATA_ADVANCE_PK PRIMARY KEY,
    DA_UUID VARCHAR(36) NOT NULL,
    DA_NAME VARCHAR(100) NOT NULL,
    DA_STATUS NUMERIC NOT NULL CONSTRAINT DATA_ADVANCE_FK2 REFERENCES DATA_STATUS(DS_ID),
    DA_CREATED TIMESTAMP(6) NOT NULL);